### ISSUE TITLE
Setup / config examples?

### ISSUE THREAD

**Issue by tjphippen** [scalient/vuex-orm-json-api#10]
I'm trying to implement vuex-orm-json-api for a new project. I have some experience with React but am a n00b to Vue. 

My issue is that there is there's no example projects for this package e.g. https://github.com/vuex-orm/vuex-orm-examples & I don't know what I'm missing, OR if there's additional config/setup steps left out because more experienced Vue developers would know/assume those steps. 

See: https://github.com/tjphippen/nova/commit/e65566edabb0ed69f247cdde6145b68cc4d7809d

I'm getting `Cannot read property $db of undefined` aka the `store`. I'm sure it's a VERY simple/obvious fix but I'm stuck. Thanks in advance!

**Comment by carsomyr** [comment]
@tjphippen Sorry for the belated reply! Are you still having trouble with this?

Looking over your code, you'll have to install Vuex ORM first by inserting
```
plugins: [VuexORM.install(database)],
```
at https://github.com/tjphippen/nova/commit/e65566edabb0ed69f247cdde6145b68cc4d7809d#diff-68cfdabf9fa2ce99fa19fdbe25785f2622056c22f88b1f846d3ac7ffffea0744L4

Can you try running your app without my adapter first, and verify that Vuex ORM itself is available?
